//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForgotPassRequest
    {
        public System.Guid Id { get; set; }
        public Nullable<int> Uid { get; set; }
        public Nullable<System.DateTime> RequestDateTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
