//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPurchase()
        {
            this.transactions = new HashSet<transaction>();
        }
    
        public long PurchaseID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string PIDSizeID { get; set; }
        public Nullable<decimal> CartAmount { get; set; }
        public Nullable<decimal> CartDiscount { get; set; }
        public Nullable<decimal> TotalPayed { get; set; }
        public string PaymentType { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
        public string MobileNumber { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
