//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblProductImages = new HashSet<tblProductImage>();
            this.tblProductSizeQuantities = new HashSet<tblProductSizeQuantity>();
        }
    
        public long PID { get; set; }
        public string PName { get; set; }
        public Nullable<decimal> PPrice { get; set; }
        public Nullable<decimal> PSelPrice { get; set; }
        public Nullable<long> PBrandID { get; set; }
        public Nullable<long> PCategoryID { get; set; }
        public Nullable<long> PSubCatID { get; set; }
        public Nullable<long> PGender { get; set; }
        public string PDescription { get; set; }
        public string PProductDetails { get; set; }
        public string PMaterialCare { get; set; }
        public Nullable<int> FreeDelivery { get; set; }
        public Nullable<int> C30DayRet { get; set; }
        public Nullable<int> COD { get; set; }
    
        public virtual tblBrand tblBrand { get; set; }
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblGender tblGender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductImage> tblProductImages { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductSizeQuantity> tblProductSizeQuantities { get; set; }
    }
}
